//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir Aplicação.
        /// </summary>
        internal static string abrirAplicaçãoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("abrirAplicaçãoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buscar.
        /// </summary>
        internal static string btnBuscar_Text {
            get {
                return ResourceManager.GetString("btnBuscar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar .
        /// </summary>
        internal static string btnCadastrar_Text {
            get {
                return ResourceManager.GetString("btnCadastrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string btnConfig_Text {
            get {
                return ResourceManager.GetString("btnConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string btnEditar_Text {
            get {
                return ResourceManager.GetString("btnEditar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover.
        /// </summary>
        internal static string btnRemover_Text {
            get {
                return ResourceManager.GetString("btnRemover.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string btnSalvarIdioma_Text {
            get {
                return ResourceManager.GetString("btnSalvarIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string cadastrarClientes_Text {
            get {
                return ResourceManager.GetString("cadastrarClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        internal static string cadastrarFuncionario_Text {
            get {
                return ResourceManager.GetString("cadastrarFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string cadastrarIngredientes_Text {
            get {
                return ResourceManager.GetString("cadastrarIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string cadastrarProdutos_Text {
            get {
                return ResourceManager.GetString("cadastrarProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string cadastrarSabores_Text {
            get {
                return ResourceManager.GetString("cadastrarSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores.
        /// </summary>
        internal static string cadastrarValores_Text {
            get {
                return ResourceManager.GetString("cadastrarValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reiniciar para aplicar o novo idioma imediatamente.
        /// </summary>
        internal static string checkBoxIdiomaReiniciar_Text {
            get {
                return ResourceManager.GetString("checkBoxIdiomaReiniciar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string clientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string configuraçõesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("configuraçõesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encerrar.
        /// </summary>
        internal static string encerrarToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("encerrarToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        internal static string funcionárioToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("funcionárioToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string groupBoxIdioma_Text {
            get {
                return ResourceManager.GetString("groupBoxIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingrediente.
        /// </summary>
        internal static string ingredienteToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("ingredienteToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio.
        /// </summary>
        internal static string inicioToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("inicioToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tradicional.
        /// </summary>
        internal static string inputCategoria_Text {
            get {
                return ResourceManager.GetString("inputCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tradicional.
        /// </summary>
        internal static string inputCategorias_Text {
            get {
                return ResourceManager.GetString("inputCategorias.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Administrador.
        /// </summary>
        internal static string inputGrupo_Text {
            get {
                return ResourceManager.GetString("inputGrupo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brasil.
        /// </summary>
        internal static string inputPais_Text {
            get {
                return ResourceManager.GetString("inputPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pequena.
        /// </summary>
        internal static string inputTamanho_Text {
            get {
                return ResourceManager.GetString("inputTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salgada.
        /// </summary>
        internal static string inputTipos_Text {
            get {
                return ResourceManager.GetString("inputTipos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SC.
        /// </summary>
        internal static string inputUF_Text {
            get {
                return ResourceManager.GetString("inputUF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ações.
        /// </summary>
        internal static string labelAcoes_Text {
            get {
                return ResourceManager.GetString("labelAcoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string labelBairro_Text {
            get {
                return ResourceManager.GetString("labelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor - Adicional Borda.
        /// </summary>
        internal static string labelBorda_Text {
            get {
                return ResourceManager.GetString("labelBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string labelCategoria_Text {
            get {
                return ResourceManager.GetString("labelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categorias.
        /// </summary>
        internal static string labelCategorias_Text {
            get {
                return ResourceManager.GetString("labelCategorias.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP.
        /// </summary>
        internal static string labelCep_Text {
            get {
                return ResourceManager.GetString("labelCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        internal static string labelCidade_Text {
            get {
                return ResourceManager.GetString("labelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        internal static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCpf_Text {
            get {
                return ResourceManager.GetString("labelCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo.
        /// </summary>
        internal static string labelGrupo_Text {
            get {
                return ResourceManager.GetString("labelGrupo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id.
        /// </summary>
        internal static string labelId_Text {
            get {
                return ResourceManager.GetString("labelId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string labelIdioma_Text {
            get {
                return ResourceManager.GetString("labelIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes Cadastrados.
        /// </summary>
        internal static string labelIngredientesCadastrados_Text {
            get {
                return ResourceManager.GetString("labelIngredientesCadastrados.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes Cadastrados.
        /// </summary>
        internal static string labelIngredientesSabores_Text {
            get {
                return ResourceManager.GetString("labelIngredientesSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        internal static string labelLogradouro_Text {
            get {
                return ResourceManager.GetString("labelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carteira de Motorista.
        /// </summary>
        internal static string labelMotorista_Text {
            get {
                return ResourceManager.GetString("labelMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome .
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número.
        /// </summary>
        internal static string labelNumero_Text {
            get {
                return ResourceManager.GetString("labelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação - Outros.
        /// </summary>
        internal static string labelObservacao_Text {
            get {
                return ResourceManager.GetString("labelObservacao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        internal static string labelPais_Text {
            get {
                return ResourceManager.GetString("labelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Produto.
        /// </summary>
        internal static string labelProduto_Text {
            get {
                return ResourceManager.GetString("labelProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipos.
        /// </summary>
        internal static string labelTipos_Text {
            get {
                return ResourceManager.GetString("labelTipos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF.
        /// </summary>
        internal static string labelUf_Text {
            get {
                return ResourceManager.GetString("labelUf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string labelValor_Text {
            get {
                return ResourceManager.GetString("labelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicação cotinua executando na bandeja.
        /// </summary>
        internal static string notifyIconSystemTray_BalloonTipText {
            get {
                return ResourceManager.GetString("notifyIconSystemTray.BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza {
            get {
                object obj = ResourceManager.GetObject("pizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_4_queijos {
            get {
                object obj = ResourceManager.GetObject("pizza 4 queijos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizzaria_tio_zé_logo_1 {
            get {
                object obj = ResourceManager.GetObject("pizzaria tio zé logo 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Principal.
        /// </summary>
        internal static string principal_Text {
            get {
                return ResourceManager.GetString("principal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto.
        /// </summary>
        internal static string produtoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabor.
        /// </summary>
        internal static string saborToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saborToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string sairToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("sairToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string sobreToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("sobreToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Clientes.
        /// </summary>
        internal static string tituloClientes_Text {
            get {
                return ResourceManager.GetString("tituloClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string tituloConfiguracoes_Text {
            get {
                return ResourceManager.GetString("tituloConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string tituloEndereco_Text {
            get {
                return ResourceManager.GetString("tituloEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Funcionários.
        /// </summary>
        internal static string tituloFuncionarios_Text {
            get {
                return ResourceManager.GetString("tituloFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Ingredientes.
        /// </summary>
        internal static string tituloIngredientes_Text {
            get {
                return ResourceManager.GetString("tituloIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listagem de Clientes.
        /// </summary>
        internal static string tituloPrincipal_Text {
            get {
                return ResourceManager.GetString("tituloPrincipal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Produtos.
        /// </summary>
        internal static string tituloProdutos_Text {
            get {
                return ResourceManager.GetString("tituloProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Sabores.
        /// </summary>
        internal static string tituloSabores_Text {
            get {
                return ResourceManager.GetString("tituloSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Valores.
        /// </summary>
        internal static string tituloValores_Text {
            get {
                return ResourceManager.GetString("tituloValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string valorToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("valorToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
